
[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
#primaryColor = "#FF4B4B"
primaryColor="#7b858e"

# Background color for the main content area.
#backgroundColor = "#0E1117"

# Background color used for the sidebar and most interactive widgets.
#secondaryBackgroundColor = "#262730"

# Color used for almost all text.
#textColor = "#FAFAFA"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"

